### ISSUE TITLE
Examples not showing up in Import dialog

### ISSUE THREAD

**Issue by colinl** [omrid01/node-red-dashboard-2-table-tabulator#2]
You example is not showing up in the Import > Examples dialog.  The reason is that the examples folder is not included in `package.json`.
To fix this add `"examples/*"` into the `files` section.  I know this as I had the same problem with my gauge node.

**Comment by colinl** [comment]
While you are in there, a couple of minor issues with the example, it is throwing linter errors as you have two unnamed functions and Function 84 has irregular indenting.

**Comment by omrid01** [comment]
Thanks Colin. The example came up on my development environment, but seems that the standard NPM installation works a little differently (this also relates to the error you reported on your other issue).
Will fix and release a new version
