### ISSUE TITLE
Unable to apply functions to tabulator attributes

### ISSUE THREAD

**Issue by Adam-Clistek** [omrid01/node-red-dashboard-2-table-tabulator#4]
I attempted to add a custom function to generate group header text (as documented [here ](https://www.tabulator.info/docs/6.3/group#setup-headers)on the tabulator documentation), but neither setting this inside the node, nor using the "tbCreateTable" command worked. in fact, I was getting the following error thrown and no data was displayed in the table:

```
Uncaught (in promise) TypeError: this.generator is not a function
    at Z.generateGroupHeaderContents (ui-tabulator.umd.js:8:21064)
```

I was using the following to generate the table:

```
msg.tbCmd = "tbCreateTable"
msg.tbInitObj={   
   "layout": "fitColumns",
    "columns": columns,
    "data": data,
    selectableRows: 1,
    groupBy: "group",
    groupHeader: "function(value, count, data, group){ return 'header'}",        
}
```
 Further more, for testing, I tried using the following table data directly within the node:

```
{
    "height":200,
    "layout": "fitColumns",
    "selectableRows": 1,
    "groupBy": "group",
    "rowSelectionChanged": "function(data, rows) { console.log('test') }",
    "columns":[
        {"field":"id", "title":"ID"},
        {"field":"value", "title":"Value"},
        {"field":"group", "title":"Group"}        
    ],
    "data":[
        {"id":0, "group":"abc", "value":123 },
        {"id":1, "group":"abc", "value":321 }
    ]
}
```

and I was not getting the function to trigger on selection changed.

Is there something that is required in order to define custom functions for the attributes of tabulator?

**Comment by omrid01** [comment]
Unfortunately, the framework of Node-RED Dashboard does not support sending function properties to dashboard widgets (such as `ui-tabulator`). There are ways to serialize/deserialize function code in messages, but this would be considered 'code injection' and will disqualify the node for security breach.
Specifically for the grouping header, you can send a formatted CSS string with the tokens `$field`, `$value` and `$count`, as explained in the on-line help, for example:
    `msg.tbGroupHeader = "$field=<span style="color:red">$value</span>, (<b>$count</b> items)"`

I realize that not supporting function properties (especially custom formatters) leaves out a lot of great Tabulator functionality. One way around this can be to set "reactor" nodes which listen to & act upon change events. Another option is simply to instantiate the Tabulator package in a ui-template node, and use its API directly.

**Comment by omrid01** [comment]
I think I found a way to allow adding function attributes in a safe way. For now, I will add this in the next release as an experimental/undocumented feature. Of course, this will put responsibility on the user to provide valid function code.

**Comment by omrid01** [comment]
Version 0.6.0 now supports functions. closing the issue.
