### ISSUE TITLE
tbCreateTable msg and subsequent updateTable msg with the same _msgid does not "persist" updated data at the dashboard client side

### ISSUE THREAD

**Issue by NIVA-IS-PSH** [omrid01/node-red-dashboard-2-table-tabulator#5]
Maybe this is a kind of a edge case, but here goes:

Consider the following  [attached flow](https://github.com/user-attachments/files/17803991/flow.json)
![image](https://github.com/user-attachments/assets/c1d56f5c-d666-4334-a91e-f7cdc960a391)
When the upper most inject node is activated a **tbCreateTable** command is send and,  delayed  300 ms, a subsequent **updateTable** is send  - and the table looks like this:
![image](https://github.com/user-attachments/assets/8e2181e2-4591-4ede-9af7-40a6e57f4f60)
The data in _Id_ and _Text_ column is sent together with **tbCreateTable** command and the data in the _Text2_ column is sent with the **updateTable** command.

If the dashboard is then refreshed by the browser the updated data disappear:
![image](https://github.com/user-attachments/assets/0c7754de-b601-4f18-93ea-245ca265bec8)

However, if the data update is initiated by the second inject node the updated data survives a browser refresh. 
Also if a "dummy" update with no data is send (the third inject node) the updated data survives a browser refresh. 

As far I have found out the reason seems to be because the **tbCcreateTable** and the **updateTable** messages share the same **_msgid** because they are chained by the delay node.

**Comment by omrid01** [comment]
You are correct in your analysis.

When the table is in **Shared** (not multi-user) mode, the latest table data image is cached in a Node-red datastore, to allow restoring the table after browser refresh or upon opening a new client. Whenever the table is updated, it shows the update and also updates the table image in the datastore.

The way Node-red dashboard works, a message from a server node (e.g. inject) is broadcasted to all open clients, hence each client will attempt to update the datastore. Since the table can hold a large amount of data, I collapse these attempts by `msg._msgid` and only update the datastore once. BTW, I do the same for table responses, otherwise if you had three open clients and issued a `getData` command from a server node, you would have received 3 identical responses.

I could perhaps add some heuristics to distinguish between messages, but the scenario you describe (sending consequent messages with same `_msgid`) seems uncommon. Do you have any specific use-case where this is needed?

**Comment by NIVA-IS-PSH** [comment]
Thank you for the explanation – it makes sense.
Knowing the behavior, it is not very difficult avoid it. 

My “use-case” is quite close to my example. It is taken from an initialization procedure when node-red is restarted or when the flow is redeployed. In the example the table is constructed with data in the two first columns (id and text) – we could call these data “master data” (data which are rarely changed) and then I update the third row (text2) with the “actual” or “dynamic” data which may or may not be persisted by node red since the restart. The first inject node is - in my real case - set to “inject once after..” to initiate the table construction shortly after restart and I then _naturally_ chained in the update part via a delay node and then the “problems” began 🙂. Knowing the behavior, it could easily be solved by having an extra inject node like this: 
![image](https://github.com/user-attachments/assets/ab1eb1b4-59bc-482d-97b0-1dff0ec5d1cb)
I was even looking for a way to change the _msgid which is impossible (I think 🤔) to do without “leaving the scope” of Node red. I came up with this solution:
![image](https://github.com/user-attachments/assets/a9dbb7ef-a676-4d66-8e9e-d6654f87fa19)

I'll stick to my initial “hunch” that this is a kind of edge case or behavior.

**Comment by omrid01** [comment]
A simpler approach (which avoids timing dependencies) would be to pass the delayed msg through a function or change node which deletes its `msg._msgid` property. When the Node-red framework sees that a sent msg has no Id, it automatically gives it a new Id. This is how you can create & send a new msg from a function node
```
let newMsg = {payload:"hello"}; // no msgid. will be assigned automatically by Node-red
return newMsg;.
```

**Comment by NIVA-IS-PSH** [comment]
I don't think it does, try this [flow](https://github.com/user-attachments/files/17842057/flow_msgid_test.json):
![image](https://github.com/user-attachments/assets/072e3d16-754c-4eed-a0b4-66f399e9864a)

> And by the way, why not set the table's "master data" as part of the table's initial configuration?

Even though they are "master data" I want to be able to upload them from the dashboard, so I have them stored in the flow context which can be updated by a file upload node from the dashboard.

**Comment by omrid01** [comment]
Interesting. It seems to be remembering the input msg Id.
However, this works:
![image](https://github.com/user-attachments/assets/c0a5f282-bea3-4970-ba1c-c61a770c99f2)

**Comment by omrid01** [comment]
Now that we understand each other... :-)
closing the issue
