### ISSUE TITLE
tbSetStyle commands are not recognized by Firefox

### ISSUE THREAD

**Issue by NIVA-IS-PSH** [omrid01/node-red-dashboard-2-table-tabulator#6]
Using the color injection examples in this nodes example set under the grouping "Table Appearance" (ref pic) nothing happens to the table if viewed in Firefox but they work fine when viewed the in Edge.

![image](https://github.com/user-attachments/assets/b29d1794-9d7e-4de1-8d92-b4704bf47bf2)

Checked console in Firefox when using any one of the three "color change" inject nodes in the section "Table Appearance" (ref pic above)
I have verified in parallel with Edge that the colors do indeed change here

Injecting "Clear styles" however makes the page flicker in Firefox an results in:

    11:39:10.826 ebf128a3b696ce43: Table destroyed ui-tabulator.umd.js:25:15627
    11:39:10.846 ebf128a3b696ce43: Table built and ready ui-tabulator.umd.js:25:14687

Attached a logfile containing the messages from when the dashboard page is loaded:
[console-export-2024-11-10_11-2-41_NEW_TAB_LOADED(1).txt](https://github.com/user-attachments/files/17957866/console-export-2024-11-10_11-2-41_NEW_TAB_LOADED.1.txt)

PS: the problem was initially addressed  [here ](https://discourse.nodered.org/t/omrid01-node-red-dashboard-2-table-tabulator-setting-colors/92989) on the Node Red forum Dashboard section

**Comment by omrid01** [comment]
Issue fixed in v0.6.1
