### ISSUE TITLE
Wrongly named variable

### ISSUE THREAD

**Issue by ardittristan** [omrid01/node-red-dashboard-2-table-tabulator#7]
https://github.com/omrid01/node-red-dashboard-2-table-tabulator/blob/fb56303e0ccc5c6fdd023b640b33104377b4a72a/ui/components/UITabulator.vue#L1181-L1187

uses `evMsg` instead of `eventMsg` making the `dataChanged` event/notification error out.

**Comment by omrid01** [comment]
good catch! thanks.
will fix

**Comment by omrid01** [comment]
Fixed in v0.6.2.
Closing the issue
